trustML/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path('user_profile/', views.editprofile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.editprofile, name='profile'),
]

trustML/trustML/urls.py
from django.urls import include, path
from . import views
from django.contrib import admin

urlpatterns = [
    path('', include('login.urls')),
    path('', include('django.contrib.auth.urls')),
    path('test/', views.test, name='test'),
    path('user_home/', views.user_home, name='user_home'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('admin_profile/', views.admin_profile, name='admin_profile'),
    path('register/', views.register, name='register'),
    path('model/', include('uploadData.urls')),
    path('result/', views.result, name='result'),
    path('data/', views.data, name='data'),
    path('run/', views.run, name='data'),
    path('clear/', views.clear, name='data'),
    path('admin/',admin.site.urls),
    path('upload/', include('uploadData.urls')),

    path('upload_model/',include('uploadModel.urls'))


]

trustML/uploadModel/urls.py
from django.urls import path

from . import views

app_name = 'upload_model'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('model_detail/<int:model_id>/',views.model_detail, name='model_detail'),
    path('uploading/',views.uploading,name='uploading'),
    path('upload_data/',views.upload_data,name="upload_data")
]

trustML/uploadModel/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.utils import timezone
import os

class ML_model(models.Model):
    creation_time = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    model_name = models.CharField(max_length=100,null = False)
    model_file = models.FileField(upload_to='ML_models/')
    specification = models.FileField(upload_to = 'ML_specifications/')
    weight = models.FileField(upload_to='ML_weights/')

@receiver(models.signals.post_delete, sender=ML_model)
def auto_delete_file_on_delete_ML_model(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.model_file:
        if os.path.isfile(instance.model_file.path):
            os.remove(instance.model_file.path)
    if instance.specification:
        if os.path.isfile(instance.specification.path):
            os.remove(instance.specification.path)
    if instance.weight:
        if os.path.isfile(instance.weight.path):
            os.remove(instance.weight.path)

trustML/uploadModel/forms.py
from django import forms
import numpy as np
from .models import ML_model
class ModelForm(forms.ModelForm):
    class Meta:
        model = ML_model
        fields = ['model_name','model_file','specification','weight','creator']

    # def clean(self):
    #     clean_data = super(ModelForm,self).clean()
    #     weights = np.genfromtxt(clean_data.get('weight'),delimiter=',',dtype=float)
    #     for weight in weights[1]:
    #         # the weight cannot be negative
    #         if weight < 0:
    #             raise ValueError("Negative weights")
    #     return clean_data

trustML/uploadModel/views.py
from .forms import ModelForm
from django.shortcuts import render,redirect
from .models import ML_model
from uploadData.models import evaluation_result, Data
from uploadData.forms import DataForm
from django.core.files import File
from django.urls import reverse
import numpy as np
from .evaluation.evaluate_model import get_confusion_matrix,get_model_and_data,get_precision_recall_accuracy
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
import os


# Create your views here.


def get_model(request):
    # if it's post then process form data
    if request.method == 'POST':
        form = ModelForm(request.POST, request.FILES)
        if form.is_valid():
            # get the creator_id
            # TODO consider transaction maybe after
            instance = ML_model(creator_id = request.user.pk,model_name = request.FILES['model_name'],\
                                model_file = request.FILES('model_file'),\
                                specification = request.FILES('specification'),\
                                weight = request.FILESI('weight'))
            instance.save()
            # if success, redirect to upload origin data
            # return a http response

def home(request):
    # get the model that user uploaded
    if User.is_authenticated:
        model_sets = ML_model.objects.filter(creator = request.user)
        context = {"model_sets":model_sets}
        return render(request,"uploadModel/home.html",context)
    else:
        # TODO redirect to login page
        redirect("http://localhost:8000/")

def model_detail(request, model_id):
    context = {}
    try:
        result_md = evaluation_result.objects.get(model  = model_id, result_type = "MD")
        result_file = result_md.result
        cf = np.loadtxt(result_file, delimiter=",", dtype=int)
        precision,recall,accuracy = get_precision_recall_accuracy(cf)
        context.update({"precision":precision})
        context.update({"recall":recall})
        context.update({"accuracy":accuracy})
        context.update({"f1_score":2*precision*recall/(precision+recall)})
    except ObjectDoesNotExist:
        result_md = None
    try:
        result_dt = evaluation_result.objects.filter(model = model_id, result_type = "DT")
    except ObjectDoesNotExist:
        result_dt = None
    model = ML_model.objects.get(pk = model_id)
    context.update({"model":model})
    if result_md is not None:
        context.update({"result_md":result_md})
    else:
        context.update({"result_md":None})
    if result_dt is not None:
        context.update({"result_dt":result_dt})
    else:
        context.update({"result_dt":None})
    return render(request,'uploadModel/model_detail.html', context)

def uploading(request):
    # import logging
    # logging.basicConfig(filename='mylog.log', level=logging.DEBUG)
    if request.method == 'POST':
        my_model_form = ModelForm(request.POST,request.FILES)
        # logging.debug(my_model_form)
        if my_model_form.is_valid():
            model_doc = my_model_form.save()
            return redirect(reverse('upload_model:model_detail', args = (model_doc.pk,)) )
        # else:
        #     return HttpResponse("Hello World")

def upload_data(request):
    # import logging
    # logging.basicConfig(filename='mylog.log', level=logging.DEBUG)
    if request.method=="POST":
        form = DataForm(request.POST,request.FILES)
        # logging.debug(form)
        # logging.debug(form.is_valid)
        if form.is_valid():
            form_object = form.save()
            data_file = request.FILES["data_file"]
            model_file = ML_model.objects.get(pk = form_object.relative_model.pk).model_file
            model, data = get_model_and_data(model_file,data_file)
            confusion_matrix = get_confusion_matrix(model,data)
            if not request.user.get_is_staff():
                original_data = Data.objects.get(data_type = 'OR', relative_model = form_object.relative_model)

            file = open("myfile.txt","w+")
            django_file = File(file)
            for row in confusion_matrix:
                django_file.write(",".join(str(number) for number in row) +"\n")

            if request.user.get_is_staff():
                type = "MD"
            else:
                type = "DT"
            result = evaluation_result(data = form_object,model = form_object.relative_model, result_type = type , result = django_file,document_count = np.sum(confusion_matrix))
            result.save()
            django_file.close()
            file.close()
            os.remove("myfile.txt")
            return redirect(reverse("upload_model:model_detail",args = (form_object.relative_model.pk,)))

trustML/uploadModel/templates/uploadModel/home.html
{% extends "interface.html" %}
{% load static %}

{% block content_block %}
    <div class="content">
        <div class = "row">
            <div class ="col-md-12">
                <div class = "card">
                    <div class="card-header">
                        <h5 class = "title">My Model</h5>
                        <p class = "category">Click to see your model evaluation</p>
                    </div>
                    <div class="card-body all-icons">
                        <div class="row">
                            {# display all the model #}
                            {% for model in model_sets %}
                              <div class="font-icon-list col-lg-2 col-md-3 col-sm-4 col-xs-6 col-xs-6">
                              {# TODO fill in href to display model #}
                              <a class="hover" href="{% url "upload_model:model_detail" model.pk %}">
                                  <div class="font-icon-detail" onmouseover="MouseOver(this)" onmouseout="MouseOut(this)" style="border-color:">
                                      <i class="now-ui-icons design_app"></i>
                                      <p>{{ model.model_name }}</p>
                                  </div>
                              </a>
                              </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class = "row">
            <div class = "col-md-12">
                <div class = "card">
                    <div class = "card-header">
                        <h5 class = "title">Upload Model</h5>
                        <p class="category">Upload new model here</p>
                    </div>
                    <div class="card-body">
                        {# TODO add post action to new model page #}
                        <form id = "TypeValidation" method = "post" enctype="multipart/form-data" action ="{% url "upload_model:uploading" %}" class="form-horizontal">
                            {% csrf_token %}
                            <div class = "row">
                                <label class="col-sm-2 col-form-label">model name</label>
                                <div class="col-sm-7">
                                    <div class="form-group">
                                        <input class="form-control" type="text" name="model_name" required="true">
                                        </input>
                                    </div>
                                </div>
                            </div>
                            <div class = "row">
                                <label class="col-sm-2 col-form-label">model file</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-2">
                                    <div class="form-group"><span class = "btn btn-success fileinput-button"><span>Choose...</span>
                                        <input name = "model_file" type="file">
                                    </span>
                                    </div>
                                    </div>
                                    <span class="form-text">The model should be stored using <code>joblib.dump()</code></span>
                                </div>
                            </div>
                            <div class = "row">
                                <label class="col-sm-2 col-form-label">specification</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-2">
                                    <div class="form-group"><span class = "btn btn-success fileinput-button"><span>Choose...</span>
                                        <input name = "specification" type="file">
                                    </span>
                                    </div>
                                    </div>
                                    <span class="form-text">Each feature including label should have a specification in metirc storing as <code>feature:[metric]</code>, separated by <code>&#44;</code></span>
                                </div>
                            </div>
                            <div class = "row">
                                <label class="col-sm-2 col-form-label">weight</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-2">
                                    <div class="form-group"><span class = "btn btn-success fileinput-button"><span>Choose...</span>
                                        <input name = "weight" type="file">
                                    </span>
                                    </div>
                                    </div>
                                    <span class="form-text">Each label should have a weight for <code>precision/recall</code>, specified as <code>label:ratio</code>, separated by <code>&#44;</code></span>
                                </div>
                            </div>
{#                            <div class="row">#}
{#                                <div class="col-sm-12">#}
{#                                    <h5>Original Data</h5>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class = "row">#}
{#                                <label class="col-sm-2 col-form-label">data description</label>#}
{#                                <div class="col-sm-7">#}
{#                                    <div class="form-group">#}
{#                                        <input class="form-control" type="text" name="description" required="false">#}
{#                                        </input>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class = "row">#}
{#                                <label class="col-sm-2 col-form-label">data file</label>#}
{#                                <div class="col-sm-10">#}
{#                                    <div class="col-sm-2">#}
{#                                    <div class="form-group"><span class = "btn btn-success fileinput-button"><span>Choose...</span>#}
{#                                        <input name = "data_file" type="file">#}
{#                                    </span>#}
{#                                    </div>#}
{#                                    </div>#}
{#                                    <span class="form-text">Original data set without header, the order of each data should follow specification order, the last column is always the actual label</span>#}
{#                                </div>#}
{#                            </div>#}
                            {# hidden value of data form #}
{#                            <input type="hidden" value="OR" name="data_type"/>#}
                            <input type="hidden" value="{{ user.pk}}" name="creator"/>
{#                            <input type="hidden" value = "{{ user.pk }}" name="uploader"/>#}
{#                            <input type="hidden" value = 0 name="relative_model">#}
                            <div class="row">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class ="col-sm-10">
                                    <div class = "form-group">
                                        <button type="submit" class = "btn btn-lg btn-primary btn-fill" >upload</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <div class="sidebar" data-color="orange">
      <!--  Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"  -->
      <div class="logo">
        <a href="{% static '../admin_home' %}" class="simple-text logo-mini">
          {{ user.email.0 }}{{ user.email.1 }}
        </a>
        <a href="#" class="simple-text logo-normal">
          {{ user.get_short_name }}
        </a>
        <div class="navbar-minimize">
          <button id="minimizeSidebar" class="btn btn-simple btn-icon btn-neutral btn-round">
            <i class="now-ui-icons text_align-center visible-on-sidebar-regular"></i>
            <i class="now-ui-icons design_bullet-list-67 visible-on-sidebar-mini"></i>
          </button>
        </div>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% static '../user_home' %}">
              <i class="now-ui-icons design_app"></i>
              <p>Models</p>
            </a>
          </li>
          <li>
            <a href="{% static '../user_profile' %}">
              <i class="now-ui-icons users_single-02"></i>
              <p>Profile</p>
            </a>
          </li>
                      {#   if it's admin then show upload model     #}
        {% if  user.get_is_staff %}
            <li class="active">
                <a href ="{% url 'upload_model:home' %}">
                <i class = "now-ui-icons files_box"></i>
                <p>My Model</p>
                </a>
            </li>
        {% endif %}
          <li>
            <a href="{% url 'logout' %}">
              <i class="now-ui-icons media-1_button-power"></i>
              <p>Log Out</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
{%  endblock %}