trustML_p03/trustML/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from . import views
app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path('user_profile/', views.editprofile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.editprofile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trustML_p03/trustML/trustML/urls.py
from django.urls import include, path
from . import views
from django.contrib import admin

urlpatterns = [
    path('', include('login.urls')),
    # needed for login page
    path('', include('django.contrib.auth.urls')),
    path('user_home/', views.user_home, name='user_home'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('models/',include('uploadModel.urls'))
]

trustML_p03/trustML/uploadModel/urls.py
from django.urls import path

from . import views

app_name = 'upload_model'
urlpatterns = [
    path('delete_model/<int:model_id>', views.delete_model, name = 'delete_model'),
    path('home/', views.home, name='home'),
    path('model_detail/<int:model_id>/',views.model_detail, name='model_detail'),
    path('uploading/',views.uploading,name='uploading'),
    path('upload_data/',views.upload_data,name="upload_data"),
    path('test/', views.test, name='test'),
    path('reward//<str:receiver>/<int:id>/<int:value>', views.reward, name='reward'),
]

trustML_p03/trustML/login/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db import models
import os
import sys
sys.path.append(os.path.abspath(os.path.join('..', 'trustML')))
from trustML.compile_solidity_utils import w3


def countNormalUsers():
    users = User.objects.all()
    count_normal = len(users)
    for u in users:
        if(u.is_superuser):
            count_normal-=1
    return count_normal


class MyUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        if extra_fields.get('is_superuser') is  True:
            user.setAddress(w3.eth.accounts[0])
        else:
            count_normal = countNormalUsers()
            print(count_normal%10+1)
            user.setAddress(w3.eth.accounts[count_normal%10+1])
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        print("Creating Superuser In Login View.py")
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('wallet_address', w3.eth.accounts[1])
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    # w3.eth.accounts[self.pk]

    wallet_address = models.CharField(max_length=42, default= w3.personal.newAccount("test"))

    image = models.ImageField(
        upload_to='user_photo/',
        blank=True,
    )
    cover = models.ImageField(
        upload_to='user_photo/',
        blank=True,
    )
    description = models.CharField(
        max_length=1000,
        default='Add a short description of yourself.'
    )
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text='Is the user allowed to have access to the admin',
    )
    is_active = models.BooleanField(
        'active',
        default=True,
        help_text= 'Is the user account currently active',
    )
    USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = ['wallet_address']
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        short_name = ''
        for c in self.email:
            if c == '@':
                break
            short_name += c
        return short_name

    def get_is_staff(self):
        return self.is_staff

    def get_bc_acc(self):
        return self.wallet_address

    def get_balance(self):
        return w3.fromWei(w3.eth.getBalance(w3.toChecksumAddress(self.wallet_address)), 'ether')

    def create_bc_acc(self, passphrase):
        self.wallet_address = models.CharField(max_length=42, default=w3.personal.newAccount(passphrase))

    def setAddress(self, address):
        self.wallet_address = address

trustML_p03/trustML/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Blockchain Boosting Trustworthy AI
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->


  <link rel="data61-icon.jpg" sizes="76x76"  href="{% static 'assets/img/data61-icon.jpg' %}">
  <link rel="icon" type="image/png"  href="{% static 'assets/img/data61-icon.jpg' %}">
  <link rel="stylesheet"  href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet"  href="{% static 'assets/css/now-ui-dashboard.css' %}">
  <link rel="stylesheet"  href="{% static 'assets/demo/demo.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

</head>

<body class=" sidebar-mini ">
  <div class="wrapper ">
    <div class="sidebar" data-color="data61">
      <!--  Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"  -->
      <div class="logo">
        <a href="#" class="simple-text logo-mini">
          {{user.email.0}}{{user.email.1}}
        </a>
        <a href="#" class="simple-text logo-normal">
          {{user.get_short_name}}
        </a>
        <div class="navbar-minimize">
          <button id="minimizeSidebar" class="btn btn-simple btn-icon btn-neutral btn-round">
            <i class="now-ui-icons text_align-center visible-on-sidebar-regular"></i>
            <i class="now-ui-icons design_bullet-list-67 visible-on-sidebar-mini"></i>
          </button>
        </div>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
        {% if request.path == "/user_home/" %}
          <li class="active">
        {% else %}
          <li>
        {% endif %}
            <a href="{% static '../user_home' %}">
              <i class="now-ui-icons design_app"></i>
              <p>Models</p>
            </a>
          </li>

          {% if request.path == "/user_profile/" %}
            <li class="active">
          {% else %}
            <li>
          {% endif %}
            <a href="{% static '../user_profile' %}">
              <i class="now-ui-icons users_single-02"></i>
              <p>Profile</p>
            </a>
          </li>
          {% if  user.get_is_staff %}
          <li>
              <a href ="{% url 'upload_model:home' %}">
              <i class = "now-ui-icons files_box"></i>
              <p>My Model</p>
              </a>
          </li>
          {% endif %}
            <li>
            <a href="{% url 'logout' %}">
              <i class="now-ui-icons media-1_button-power"></i>
              <p>Log Out</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute bg-info ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#">Boosting Trust in ML with Blockchain</a>
          </div>

        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-sm">
      </div>
      <div class="content">
        {% block content_block %}
        {% endblock %}
      </div>

      <footer class="footer">
        <div class="container-fluid">

          <div class="copyright" id="copyright">
            &copy;
            <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Ispired by
            <a class="text-info" href="https://www.data61.csiro.au/" target="_blank">Data61</a>. Created by
            <a class="text-info" href="https://bitbucket.org/p03b/blockchains-boosting-trustworthy-ai/overview" target="_blank">P03B</a>.
          </div>
        </div>
      </footer>

    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/moment.min.js' %}"></script>
    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="{% static 'assets/js/plugins/bootstrap-switch.js' %}"></script>
    <!--  Plugin for Sweet Alert -->
    <script src="{% static 'assets/js/plugins/sweetalert2.min.js' %}"></script>
    <!-- Forms Validations Plugin -->
    <script src="{% static 'assets/js/plugins/jquery.validate.min.js' %}"></script>
    <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
    <script src="{% static 'assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="{% static 'assets/js/plugins/bootstrap-selectpicker.js' %}"></script>
    <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
    <script src="{% static 'assets/js/plugins/bootstrap-datetimepicker.js' %}"></script>
    <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
    <script src="{% static 'assets/js/plugins/jquery.dataTables.min.js' %}"></script>
    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="{% static 'assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
    <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="{% static 'assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
    <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
    <script src="{% static 'assets/js/plugins/fullcalendar.min.js' %}"></script>
    <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
    <script src="{% static 'assets/js/plugins/jquery-jvectormap.js' %}"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{% static 'assets/js/plugins/nouislider.min.js' %}"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <!-- Chart JS -->
    <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
    <!--  Notifications Plugin    -->
    <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{% static 'assets/js/now-ui-dashboard.min.js' %}" type="text/javascript"></script>
    <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
    <script src="{% static 'assets/demo/demo.js' %}"></script>
    <script type="text/javascript">
      function MouseOver(obj)
      {
  		// obj.style.borderColor = "rgb(249,99,50)";
      obj.style.borderColor = "rgb(92,207,143)";
      }

      function MouseOut(obj)
      {
  		obj.style.borderColor = "rgb(229, 229, 229)";
      }
  </script>

</body>

</html>

trustML_p03/trustML/templates/interface.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8" />
  <!-- <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png"> -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Blockchain Boosting Trustworthy AI
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link rel="data61-icon.jpg" sizes="76x76"  href="{% static 'assets/img/data61-icon.jpg' %}">
  <link rel="icon" type="image/png"  href="{% static 'assets/img/data61-icon.jpg' %}">
  <link rel="stylesheet"  href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet"  href="{% static 'assets/css/now-ui-dashboard.css' %}">
  <link rel="stylesheet"  href="{% static 'assets/demo/demo.css' %}">
  <style type="text/css">
    a:hover{ text-decoration:none;}
  </style>

</head>

<body class=" sidebar-mini ">
  <div class="wrapper ">
  {% block sidebar %}
    {% endblock %}
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute bg-primary ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#">Models</a>
          </div>

        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-sm">
      </div>
    {% block content_block %}
    {% endblock %}
    <footer class="footer">
      <div class="container-fluid">
      </div>
    </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{% static 'assets/js/plugins/bootstrap-switch.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'assets/js/plugins/sweetalert2.min.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'assets/js/plugins/jquery.validate.min.js' %}"></script>
  <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'assets/js/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'assets/js/plugins/bootstrap-datetimepicker.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
  <script src="{% static 'assets/js/plugins/jquery.dataTables.min.js' %}"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'assets/js/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'assets/js/plugins/jquery-jvectormap.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'assets/js/plugins/nouislider.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/now-ui-dashboard.min.js' %}" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>

  <script type="text/javascript">
    function MouseOver(obj)
    {
		// obj.style.borderColor = "rgb(249,99,50)";
    obj.style.borderColor = "rgb(92,207,143)";
    }

    function MouseOut(obj)
    {
		obj.style.borderColor = "rgb(229, 229, 229)";
    }
</script>
<script>
    function setFormValidation(id) {
      $(id).validate({
        highlight: function(element) {
          $(element).closest('.form-group').removeClass('has-success').addClass('has-danger');
          $(element).closest('.form-check').removeClass('has-success').addClass('has-danger');
        },
        success: function(element) {
          $(element).closest('.form-group').removeClass('has-danger').addClass('has-success');
          $(element).closest('.form-check').removeClass('has-danger').addClass('has-success');
        },
        errorPlacement: function(error, element) {
          $(element).append(error);
        },
      });
    }

    $(document).ready(function() {
      setFormValidation('#RegisterValidation');
      setFormValidation('#TypeValidation');
      setFormValidation('#LoginValidation');
      setFormValidation('#RangeValidation');
    });
  </script>
</body>

</html>

trustML_p03/trustML/templates/user_home.html
{% extends "base.html" %}
{% load static %}

{% block content_block %}
  <div class="row">

    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h5 class="title text-info">Models</h5>
          <p class="category">Choose a model and start to evaluate your data.</p>
        </div>
        <div class="card-body all-icons">
          <div class="row">

            {# display all the models #}
            {% for model in model_sets %}
              <div class="font-icon-list col-lg-2 col-md-3 col-sm-4 col-xs-6 col-xs-6">
              {# TODO fill in href to display model #}
              <a class="hover text-info" href="{% url "upload_model:model_detail" model.pk %}">
                  <div class="font-icon-detail" onmouseover="MouseOver(this)" onmouseout="MouseOut(this)" style="border-color:">
                      <i class="now-ui-icons design_app text-info"></i>
                      <p>{{ model.model_name }}</p>
                  </div>
              </a>
              </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock content_block %}

trustML_p03/trustML/templates/user_profile.html
{% extends "base.html" %}
{% load static %}

{% block content_block %}
  <div class="row">

    <div class="col-md-4">
      <div class="card card-user">
        <div class="image">
          {% if user.cover %}
              <img src="{{ user.cover.url }}" alt="...">
          {% else %}
              <img  src="{% static 'assets/img/cover.png' %}" alt="...">
          {% endif %}
        </div>
        <div class="card-body">
          <div class="author">

              {% if user.image %}
                  <img class="avatar border-gray" src="{{ user.image.url }}" alt="...">
              {% else %}
                  <img class="avatar border-gray" src="{% static 'assets/img/default-avatar.png' %}" alt="...">
              {% endif %}
              <h5 class="text-info">{{user.get_short_name}}</h5>

            <p class="description">
              {{user.email}}
            </p>
          </div>
          <p class="description text-center">
            {{ user.description }}
          </p>
        </div>
        <hr><br>
        <div style="padding:10px;">
          <p class="description text-center">
            <i class="fas fa-address-card"></i>
            <b> {{ user.get_bc_acc }} </b>
          </p>
          <p class="description text-center">
            <i class="fab fa-ethereum"></i> <br>
            <b>{{ user.get_balance }}</b>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title text-info text-center">Edit Profile</h5>
        </div>
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div class="row">
              <div class="col-md-2"></div>
              <label class="col-md-2 col-form-label text-right">Description</label>
              <div class="col-md-4">
                <input type="text" class="form-control" name="description" value='{{ user.description }}' maxlength="1000" required="" id="id_description">
              </div>
            </div>
            <div class="row">
              <div class="col-md-2"></div>
              <label class="col-md-2 col-form-label text-right">Wallet Address</label>
              <div class="col-md-4">
                <input type="text" class="form-control" name="wallet_address" value="{{ user.wallet_address }}" maxlength="40" required="" id="id_wallet_address" readonly>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2"></div>
              <label class="col-md-2 col-form-label text-right">Cover</label>
              <div class="col-md-4">
                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                  <div class="fileinput-new thumbnail">
                    <img src="../../static/assets/img/image_placeholder.jpg" alt="...">
                  </div>
                  <div class="fileinput-preview fileinput-exists thumbnail"></div>
                    <div>
                      <span class="btn btn-rose btn-round btn-file">
                      <span class="fileinput-new">Choose</span>
                      <span class="fileinput-exists">Change</span>
                        <input type="file" name="cover" accept="image/*" id="id_cover">
                      </span>
                      <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput">
                        <i class="fa fa-times"></i>
                        Delete
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2"></div>
              <label class="col-md-2 col-form-label text-right">Image</label>
              <div class="col-md-4">
                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                  <div class="fileinput-new thumbnail">
                    <img src="../../static/assets/img/image_placeholder.jpg" alt="...">
                  </div>
                  <div class="fileinput-preview fileinput-exists thumbnail"></div>
                    <div>
                      <span class="btn btn-rose btn-round btn-file">
                      <span class="fileinput-new">Choose</span>
                      <span class="fileinput-exists">Change</span>
                        <input type="file" name="image" accept="image/*" id="id_image">
                      </span>
                      <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput">
                        <i class="fa fa-times"></i>
                        Delete
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                  <button name="change_profile" type="submit" class="btn btn-info btn-round btn-lg btn-block">Submit</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">
              <h5 class="title text-info text-center">Change Password</h5>
            </div>
            <div class="card-body">
              <form method="POST">
                {% csrf_token %}
                <!-- {{ change_pw_form.as_p }} -->
                <div class="row">
                  <div class="col-md-2"></div>
                  <label class="col-md-2 col-form-label text-right">Old Password</label>
                  <div class="col-md-4">
                    <input type="password" class="form-control" name="old_password" autofocus="" required="" id="id_old_password">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2"></div>
                  <label class="col-md-2 col-form-label text-right">New Password</label>
                  <div class="col-md-4">
                    <input type="password" class="form-control" name="new_password1" required="" id="id_new_password1">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2"></div>
                  <label class="col-md-2 col-form-label text-right">Confirm Password</label>
                  <div class="col-md-4">
                    <input type="password" class="form-control" name="new_password2" required="" id="id_new_password2">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4"></div>
                  <div class="col-md-4">
                    <button name="change_pw" type="submit" class="btn btn-info btn-round btn-lg btn-block mb-3">Submit</button>
                  </div>
                </div>
              </form>
              <ul class="messages">
                <li>Your password can't be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can't be a commonly used password.</li>
                <li>Your password can't be entirely numeric.</li>
                {% if messages %}
                  {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                  {% endfor %}
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}